#!/bin/bash
###################################################
#
#  Name: configure_ec2_node
#  Purpose: Sets up base config and utils for ec2 nodes
#  Author: Shane Kumpf
#
###################################################

#
# Base variables
#
SCRIPT_NAME=`basename $0`
SCRIPT_DIR=`cd $(dirname $0) && pwd`
SRC_DIR=$SCRIPT_DIR/${SCRIPT_NAME}.f

#
# Varibles
#
work_dir="/tmp/work"

#
# Functions
#
function usage
{
    echo "Usage: $SCRIPT_NAME"
    exit 1
}

#
# Validation
#
if [ `id -un` != "ec2-user" ]; then
    echo "ERROR: Must run as ec2-user"
    exit 1
fi

#
# Main
#
echo -e "\nStarting $SCRIPT_NAME at `date`"

# Setup the work dir
if [ ! -d "$work_dir" ]; then
    echo -e "\n#####  Creating work directory $work_dir"
    mkdir -p $work_dir || exit 1
    echo "SUCCESS"
fi

# Setup the EPEL repo
echo -e "\n#####  Setting up EPEL yum repo"
(cd $work_dir && wget -N http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm) || exit 1
sudo rpm -ivh $work_dir/epel-release-6-8.noarch.rpm

# Install git
echo -e "\n#####  Installing git"
sudo yum install -y git || exit 1
echo "SUCCESS"

# Install pip
echo -e "\n#####  Installing pip"
sudo yum install -y python-pip || exit 1
echo "SUCCESS"

# Install EC2 SSH
echo -e "\n#####  Installing ec2-ssh"
sudo pip install ec2-ssh || exit 1
sudo cp $SRC_DIR/ec2-ssh /usr/bin/ || exit 1 # Copy customized version
sudo cp $SRC_DIR/ec2-host-int /usr/bin/ || exit 1 # Copy customized version
echo "SUCCESS"

# Set the new hostname using the tag from EC2
new_hostname=`ec2-host-int | grep $(hostname -f) | awk '{print $1}'`
echo -e "\n#####  Setting hostname to $new_hostname"
sudo sed -i 's|HOSTNAME=.*|HOSTNAME='$new_hostname'|g' /etc/sysconfig/network || exit 1
cat /etc/sysconfig/network
echo "SUCCESS"

# disable selinux
echo -e "\n#####  Disabling SELinux"
sudo sed -i 's|SELINUX=.*|SELINUX=disabled|g' /etc/sysconfig/selinux || exit 1
cat /etc/sysconfig/selinux
echo "SUCCESS"

# disable iptables
echo -e "\n#####  Disabling IPTables"
sudo chkconfig iptables off || exit 1
sudo chkconfig ip6tables off || exit 1
echo "SUCCESS"

echo -e "\nFinished $SCRIPT_NAME at `date`"

echo "Rebooting in 30 seconds...."
sleep 30
shutdown -ry now
